openapi: 3.0.3
info:
  title: XML Parser & AI Analyzer Service
  version: 1.0.0
  description: Микросервис, который будет ежедневно получает XML-файл с данными о
    продажах, обрабатывает его и генерирует аналитический отчет с помощью LLM.
paths:
  /api/products/:
    get:
      operationId: products_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProductList'
          description: ''
  /api/products/{id}/:
    get:
      operationId: products_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - products
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /api/sales_analyses/:
    get:
      operationId: sales_analyses_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - sales_analyses
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSalesAnalysisList'
          description: ''
  /api/sales_analyses/{id}/:
    get:
      operationId: sales_analyses_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - sales_analyses
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesAnalysis'
          description: ''
components:
  schemas:
    PaginatedProductList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    PaginatedSalesAnalysisList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/SalesAnalysis'
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product_id:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        name:
          type: string
          maxLength: 255
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: 0
          format: int64
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,10}(?:\.\d{0,2})?$
        category:
          type: string
          maxLength: 255
        sales_date:
          type: string
          format: date
      required:
      - category
      - id
      - name
      - price
      - product_id
      - quantity
      - sales_date
    SalesAnalysis:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        date:
          type: string
          format: date
          description: Дата продаж, для которых выполнен анализ
        analysis_report:
          type: string
          description: Аналитический отчёт, сгенерированный LLM
        created_at:
          type: string
          format: date-time
          readOnly: true
          description: Дата и время создания отчёта
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
          readOnly: true
      required:
      - analysis_report
      - created_at
      - date
      - id
      - products
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
